language: python
script:
  - touch foo
  - export TAGNAME=$(grep -P "^## .*?" CHANGELOG.md -m1 | awk '{print $2}' |awk '{print $1}')
  - git tag $TAGNAME
  - git push --tags
#deploy:
#  provider: pypi
#  user: $pypiusername
#  password: $pypipassword
#  distributions: "sdist"
#  on:
#    branch: master
