language: python
script:
  - touch foo
before_deploy:
  - export TAGNAME=$(grep -P "^## .*?" CHANGELOG.md -m1 | awk '{print $2}' |awk '{print $1}')
  - git tag $TAGNAME 
deploy:
  provider: releases
  user: lavanyaj23
  password: $gitpwd
  skip_cleanup: true
  on:
    tags: true
deploy:
  - provider: pypi
    user: $pypiusername
    password: $pypipassword
    distributions: "sdist"
    on:
      branch: master
