language: python
script:
  - touch foo
before_deploy:
  - export TRAVIS_TAG=$(grep -P "^## .*?" CHANGELOG.md -m1 | awk '{print $2}' |awk '{print $1}')
  - git tag $TRAVIS_TAG 
deploy:
  provider: releases
  user: lavanyaj23
  password: $gitpwd
  skip_cleanup: true
  on:
    tags: true
    branch: master
deploy:
  - provider: pypi
    user: $pypiusername
    password: $pypipassword
    distributions: "sdist"
    on:
      branch: master
